Fix docs & scripts
oceanprotocol/aquarius pull request #1004
Opened 2023-03-27 19:03 UTC by mariacarmina

## Description

Fix docs. Update scripts env vars. Removed deprecated exceptions.

## Is this PR related with an open issue?

Related to Issue #1005 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-03-28 05:54 UTC, calina-c commented on aquarius/events/events_monitor.py
> -                except elasticsearch.exceptions.ElasticsearchException as es_err:
I think these should be treated separately. If it is not an ElasticsearchException, please log another error.

2023-03-28 05:57 UTC, calina-c requested changes
These all seem to be local changes, lgtm but are we sure the problem with indexing is not related to some server configuration? That should be in the scope of fixing the indexing. Did you compare your settings with @md00ux's live ones?

2023-03-28 17:32 UTC, mariacarmina commented
> These all seem to be local changes, lgtm but are we sure the problem with indexing is not related to some server configuration? That should be in the scope of fixing the indexing. Did you compare your settings with @md00ux's live ones?

The settings from @md00ux didn't seem to need the env vars that I added in `exportlocal.sh`. I can revert changes from `exportlocal.sh` if so.

2023-03-29 05:55 UTC, calina-c commented on aquarius/events/events_monitor.py
> -                except elasticsearch.exceptions.ElasticsearchException as es_err:
oh, ok then

2023-03-29 05:56 UTC, calina-c approved these changes

2023-03-29 20:00 UTC, merged