Add price.adddress again for pools
oceanprotocol/aquarius pull request #424
Opened 2021-03-24 00:18 UTC by kenbodnar

## Description

Aquarius issue #388 requested removing price.address and replacing it with price.exchange_id. However price.address is needed for pools. It was added back in for the appropriate cases.

## Is this PR related with an open issue?

Related to Issue #

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

#### Funny gif

![Put a link of a funny gif inside the parenthesis-->]()

2021-03-29 06:01 UTC, calina-c requested changes

2021-03-29 06:01 UTC, calina-c commented on aquarius/events/metadata_updater.py
>              price_dict.update({"address": "", "type": ""})
these two lines can be combined. The "type" key and its empty value are just repeated. Please add "exchange_id": "" to the original update instruction.

2021-03-31 07:29 UTC, calina-c commented
@reviewers: I just combined Ken's dict update statements into one, but I also did a tiny change. Not sure if it is correct. In one instance, he was setting the "type" to "" but exchange_id was populated. I assumed type needs to be "exchange" if an "exchange_id" is set. Is that correct? 

https://github.com/oceanprotocol/aquarius/pull/424/commits/67a56188366598dfe03a982c379cd8ff007b30ad

2021-04-01 09:14 UTC, alexcos20 commented
Let's keep it as it is for now, from our market you can create either a pool or a fre.
Will continue later

2021-04-01 11:07 UTC, calina-c approved these changes

2021-04-01 11:07 UTC, merged

2021-04-02 22:12 UTC, DMats commented
The changes in this PR fix #410

2021-04-02 22:19 UTC, DMats commented
Closes #410

(trying to get Zenhub to link them together)