Add v4 DDO structure validator
oceanprotocol/aquarius pull request #597
Opened 2021-10-11 07:39 UTC by calina-c

Closes #583. Works seamlessly with v3, can be merged to main.

2021-11-03 15:35 UTC, DMats commented
@calina-c Can you add a list of the primary changes included in this PR to the PR description (the first comment)? I think that would make it easier to review.

2021-11-03 16:50 UTC, DMats commented on aquarius/ddo_checker/schemas/v4/metadata_remote_v4.0.0.json
> +    "created": {
`created` and `updated` are missing `type`

2021-11-03 19:15 UTC, DMats commented on aquarius/ddo_checker/schemas/v4/metadata_remote_v4.0.0.json
> +                      "default": 0,
This default of `0` is not valid against the `"type": "string"`

2021-11-03 20:03 UTC, DMats requested changes

2021-11-03 20:03 UTC, DMats commented on aquarius/ddo_checker/schemas/v4/metadata_remote_v4.0.0.json
> +              "type": "string"
Most other keys of `"type": "string"` include a pattern that disallows multi-line strings `"pattern": "^(.*)$"`. This seems like a sensible restriction, so for consistency, I'd like to see it applied to all keys of `"type": "string"` in this file.

2021-11-04 11:01 UTC, mihaisc commented
`Status` is not updated https://github.com/oceanprotocol/aquarius/blob/792e59e53cf13859fad44a686ff3f66b6584fda8/aquarius/ddo_checker/schemas/v4/metadata_remote_v4.0.0.json#L437

https://deploy-preview-783--docs-oceanprotocol.netlify.app/concepts/did-ddo/#status

2021-11-04 11:48 UTC, merged