update ERC721 template
oceanprotocol/aquarius pull request #656
Opened 2021-12-27 14:43 UTC by alexcos20

Closes #654

2021-12-27 17:12 UTC, alexcos20 commented
so, we hit a circular dependency.  
Aqua needs Provider (with updated code).  But in order to update Provider, we need Aqua with updated code.

So both PRs ([this ](https://github.com/oceanprotocol/aquarius/pull/656) and https://github.com/oceanprotocol/provider/pull/311) should be merged in the same time.

To test it , do the following:
 - clone provider, build your own image
 - clone aquarius, build your own image
 - update barge to use those images , instead of default aqua & provider
 - Run the tests
 - Approve the PR

2021-12-27 19:07 UTC, DMats reviewed
I followed the instructions https://github.com/oceanprotocol/aquarius/pull/656#issuecomment-1001662168 and also tweaked the IP addresses so the tests could connect to barge, but was unable to make the Aquarius tests pass.

To make the Aquarius tests connect to barge, I had to update `pytest.ini` like so:

```patch
-    D:DB_HOSTNAME = 127.0.0.1
+    D:DB_HOSTNAME = 172.15.0.6
    ...
-    D:EVENTS_RPC = http://127.0.0.1:8545
-    D:NETWORK_URL = http://127.0.0.1:8545
+    D:EVENTS_RPC = http://172.15.0.3:8545
+    D:NETWORK_URL = http://172.15.0.3:8545
```

EDIT: 

The errors look similar to the ones that appear in the Github checks. (with the exception of `test_get_web3_connection_provider` which fails because of the tweak described above)

```pytest
========================================================================== short test summary info ===========================================================================
FAILED tests/test_assets_api.py::test_resolveByDtAddress - assert 0 > 0
FAILED tests/test_assets_api.py::test_get_assets_names - AssertionError: did name not found.
FAILED tests/test_events.py::test_publish_and_update_ddo - KeyError: 'id'
FAILED tests/test_events.py::test_publish_and_update_ddo_with_lzma - KeyError: 'id'
FAILED tests/test_events.py::test_publish_and_update_ddo_with_lzma_and_encrypt - KeyError: 'id'
FAILED tests/test_events.py::test_publish_and_update_ddo_unencrypted - KeyError: 'id'
FAILED tests/test_events.py::test_publish - KeyError: 'id'
FAILED tests/test_events.py::test_publish_and_update_ddo_rbac - KeyError: 'id'
FAILED tests/test_events.py::test_get_last_processed_block - assert 31 == 0
FAILED tests/test_events.py::test_order_started - KeyError: 'stats'
FAILED tests/test_processors.py::test_process_fallback - KeyError: 'id'
FAILED tests/test_purgatory.py::test_purgatory_with_assets - KeyError: 'stats'
FAILED tests/test_purgatory.py::test_purgatory_with_accounts - KeyError: 'stats'
FAILED tests/test_util.py::test_get_web3_connection_provider - AssertionError: assert 'http://172.15.0.3:8545' == 'http://127.0.0.1:8545'
```

2021-12-28 14:13 UTC, calina-c requested changes
just a few of my minor quirks, please :)
otherwise looks great!

2021-12-28 14:13 UTC, calina-c commented on aquarius/app/assets.py
> +from hashlib import sha256
please alphabetize imports in groups :)

2021-12-28 14:13 UTC, calina-c commented on aquarius/app/assets.py
> +        wallet = Account.from_key(private_key=pk)
can you please name this provider_wallet like everywhere else? I also think there is an util callled get_provider_wallet or provider_wallet that would help here

2021-12-28 14:13 UTC, calina-c commented on aquarius/app/assets.py
> +        raw = request.get_data()
my opinion is to move the contents of this if to a different function and only call it later, when we need to return it (line 362 currently, when doing "if valid")

2021-12-28 14:13 UTC, calina-c commented on tests/helpers.py
> +        _response = client_method(url, content_type="application/octet-stream")
I think you can return this directly, without assigning `_response`. Then later, you can remove the "else" keyword and return the other value directly.

2021-12-28 14:13 UTC, calina-c commented on tests/test_validate_api.py
> +from tests.helpers import run_request_octet
here as well, please organise imports.

2021-12-28 20:32 UTC, calina-c approved these changes

2021-12-28 20:34 UTC, merged