Updated decrypt event. Added UTC timezone. Updated private keys from …
oceanprotocol/aquarius pull request #720
Opened 2022-03-01 17:59 UTC by mariacarmina

## Description

Updated decrypt event. Added UTC timezone. Updated private keys from pytest.ini

## Is this PR related with an open issue?

Related to Issue #713 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Checklist:

- [X] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] Documentation

2022-03-02 23:46 UTC, DMats reviewed
What was the fix? The it `utcnow` stuff or the updated private keys?  Is it possible to revert the private key change?

2022-03-03 08:32 UTC, calina-c requested changes
Looks good, just one small change.

2022-03-03 08:32 UTC, calina-c commented on tests/test_purgatory.py
> -    in_one_hour = datetime.now() + timedelta(hours=1)
nope, here you don't need it. This is not a nonce-related thing, it's a tool to set the time for the tests. Keep "now" here.

2022-03-03 12:12 UTC, calina-c commented on aquarius/events/purgatory.py
> +        now = int(datetime.utcnow().timestamp())
same here, this is internal.

2022-03-03 13:42 UTC, calina-c commented on aquarius/events/decryptor.py
>  def decrypt_ddo(w3, provider_url, contract_address, chain_id, txid, hash):
@mariacarmina as part of https://github.com/oceanprotocol/provider/pull/384 I've added dataNftAddress as required. Please send it as part of the payload.

2022-03-03 14:27 UTC, mariacarmina commented
> What was the fix? The it `utcnow` stuff or the updated private keys? Is it possible to revert the private key change?

@DMats, in other repos the UTC timezone was imposed and I needed to add in aqua as well. Other than that, I've changed all the private keys to make sure that each repo has different private keys => different accounts => higher nonce, because it was a possibility that the same account has done another tx in the past which makes it lower than the `db_nonce` from provider repo.

2022-03-04 07:47 UTC, calina-c approved these changes

2022-03-04 12:58 UTC, alexcos20 approved these changes

2022-03-04 13:12 UTC, merged