Adds single filter.
oceanprotocol/aquarius pull request #780
Opened 2022-04-06 08:56 UTC by calina-c

2022-04-06 14:13 UTC, DMats requested changes

2022-04-06 14:13 UTC, DMats commented on aquarius/app/util.py
> +            return response.json()
If the status_code is not 200, then I think we should log a warning.

2022-04-06 14:13 UTC, DMats commented on tests/test_util.py
> +        response.json.return_value = {"this_is": "SPARTAAA!"}
:laughing:

2022-04-07 09:38 UTC, alexcos20 approved these changes

2022-04-08 06:30 UTC, merged